layout_spectrum: 0.8280702
typography_spectrum: 0.9874518
color:
  saturation: 0.01248503
  lightness: 0.2109077
  brandStrength: 0.4976372
  rhythmicContrast: 0.8053958
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Peet
